### ISSUE TITLE
Machine Tool Accessories: There's no pagination for more than 12 items

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/K2-Engineering#13]
Comment:  Images or logos are not arranged properly as well.
URL: http://k2engineering.stage.titanweb.com.au/product-cat/machine-tool-accessories/

Screenshot(s):
![machine tool accessories - 01](https://cloud.githubusercontent.com/assets/12888048/8173909/8a27ab00-1407-11e5-9776-0cc92c50accf.jpeg)

**Comment by rexcebudigital** [comment]
I don't see the issue on my end. Please recheck. Thanks.

**Comment by romatitan** [comment]
There's no pagination for more than 12 items. This issue is still reproducible
Here's a new screenshot(s) for your reference.
URL: http://k2engineering.stage.titanweb.com.au/product-cat/machine-tool-accessories/
Screenshot(s):
![machine tool accessories - 03](https://cloud.githubusercontent.com/assets/12888048/8322176/d1f96916-1a63-11e5-9acb-5e608e3d7ba4.jpeg)

**Comment by romatitan** [comment]
There are 17 items under Machine Tool Accessories in Admin but the page displays 12 items only.

Screenshot(s):
![machine tool accessories - 04](https://cloud.githubusercontent.com/assets/12888048/8399358/47997c04-1e3f-11e5-81d4-4a220636c0fb.jpg)

**Comment by rexcebudigital** [comment]
I still don't see this error on my end. This screenshot is taken from the "STAGE URL"
![screenshot jpg 1655x1033](https://cloud.githubusercontent.com/assets/11186391/8400708/aa52eacc-1e55-11e5-9653-bbdd5210c8a4.png)
