### ISSUE TITLE
Resources: There's no file added, but when you click the item, it will open the "Resources" page in new tab

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/K2-Engineering#18]
URL: http://k2engineering.stage.titanweb.com.au/resources/

Step to Replicate:
1. In WP admin,  Click Pages > Resources
2. Add row for a new Resources File Repeater
   Input text/title for Resources PDF File Name
    Do not add Resources PDF File
3. Go to the URL mention above
4. Click the Resources item you have created
5. Observe that when you click the item, it will open the "Resources" page in new tab.

Screenshot(s):
![resources - 02](https://cloud.githubusercontent.com/assets/12888048/8174859/88b0bb42-1414-11e5-8d89-72445f6ac1de.jpg)

**Comment by rexcebudigital** [comment]
Now fixed.
It should not display if there's no file name and file added.
