### ISSUE TITLE
Homepage: Active / Hover state was not implemented on buttons/icons and links

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/K2-Engineering#19]
Comment: All active / hover states must be implemented for buttons and links as per standard.
URL: http://k2engineering.stage.titanweb.com.au/

Screenshot(s):
![homepage - 04](https://cloud.githubusercontent.com/assets/12888048/8176290/73a038ba-142b-11e5-8b19-fe00afba125a.jpg)

**Comment by rexcebudigital** [comment]
Please always remember that the mobile devices doeskin have a "Hover" effect.
I have attach a screenshot showing the clicked menu item is on active state.

![screenshot1](https://cloud.githubusercontent.com/assets/11186391/8248053/0235acaa-168d-11e5-8222-7746013f2125.jpg)
