### ISSUE TITLE
In homepage, Lorem ipsum text was used for the browser title tag.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/K2-Engineering#20]
URL: http://k2engineering.stage.titanweb.com.au/

Screenshot(s):
![homepage - 03](https://cloud.githubusercontent.com/assets/12888048/8175254/3502064e-141a-11e5-9256-37667daadd50.jpg)

**Comment by rexcebudigital** [comment]
The title is automatically changed when we set a new page title.
What I did is I changed the homepage title into a sample page title. :)
