### ISSUE TITLE
Homepage: Mobile number was missing in responsive design view.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/K2-Engineering#23]
Testing: Cross-Browsing, Responsive test
URL:"http://k2engineering.stage.titanweb.com.au/"
Browser affected: Opera 12, IE 11
Screenshot(s):
![homepage - 05](https://cloud.githubusercontent.com/assets/12888048/8177174/86bd96b4-1434-11e5-958f-19a056c692e4.jpg)

**Comment by rexcebudigital** [comment]
*On my end my opera version is 30 and its not an issue on my end using the updated version of the opera.

*On IE 11 is now fixed.
