### ISSUE TITLE
Contact Us: Error occurs when you click "Contact Us"

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/K2-Engineering#25]
Additional: Similar with this, an error occurs as well when you click the "Submit" button in Contact page form.
Affected Browser: IE
URL: http://k2engineering.stage.titanweb.com.au/contact-us/
Screenshot(s):
![contact - 02](https://cloud.githubusercontent.com/assets/12888048/8179128/1ba391ea-1447-11e5-8ce6-7a34851b1b92.jpg)

**Comment by rexcebudigital** [comment]
Please follow this to solve the issue.

This bug occur because we are just using an emulator. Kindly let me know if this bug is not solve. 

![screenshot1](https://cloud.githubusercontent.com/assets/11186391/8246118/833de88e-166b-11e5-9b59-8492e3faf261.jpg)
