### ISSUE TITLE
Gallery did not follow the standard layout

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/K2-Engineering#29]
URL: http://k2engineering.stage.titanweb.com.au/gallery/
Reference: https://knowledgebase.titanweb.com.au/implementation-practices/nggallery-implementation-practices/gallery-layout-and-styles

Screenshot(s):
![gallery - 05](https://cloud.githubusercontent.com/assets/12888048/8198598/85bc28d2-14db-11e5-9367-13fce1853ab0.jpeg)

**Comment by romatitan** [comment]
Compact album style/layout should be the same with the gallery.

**Comment by rexcebudigital** [comment]
As far as I know with this standard. Album height and width will only be the same with the gallery.
