### ISSUE TITLE
Gallery: Image in fancybox did not fit to the center page

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/K2-Engineering#32]
Summary: Image in fancybox was not aligned at the center/ fit to the center page when you open/click the image from landscape view then rotate or change the view layout to portrait.
Affected device(s): iPad Air
URL: http://k2engineering.stage.titanweb.com.au/gallery/

Screenshot(s):
![gallery - 06](https://cloud.githubusercontent.com/assets/12888048/8201282/ee5d1c5e-1501-11e5-89f8-a14a45f9e0be.jpg)

Step to Replicate:
1. Go to "http://k2engineering.stage.titanweb.com.au/gallery/"
2. In landscape view, open/click the image in the gallery
3. Rotate or change the view to Portrait
4. Observe the image in fancybox did not fit to the center page.

**Comment by rexcebudigital** [comment]
No issues were found while checking on chrome device tool and ipad on my end. Please recheck. 
Thanks.

**Comment by romatitan** [comment]
This issue is reproducible.
Affected device/s: iPad Air
Step to Replicate:
1. Clear Cookies and Data of the browser (safari)
2. Go to "http://k2engineering.stage.titanweb.com.au/gallery/"
3. In landscape view, click the image in the gallery ( the image will open in fancybox) then,
4. Rotate or change the view to Portrait
5. Observe the image in fancybox did not fit to the center page.

**Comment by rexcebudigital** [comment]
iPad AIR IOS version 8.3
