### ISSUE TITLE
Question: "View Range" button should be link in what page/s?

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/K2-Engineering#34]
Does each banner page link should be linked in different page/s ( Contact Us, Resources, Catalogues)?

Please confirm with leads and update the scope accordingly.

**Comment by rexcebudigital** [comment]
Yup, I was just following the design brief.

**Comment by romatitan** [comment]
According to your Team Lead, as for now link the view range to Product page alone.

**Comment by rexcebudigital** [comment]
Its not set to products page.
