### ISSUE TITLE
Resources:  The resources item(s) opposite to each other should be arrange properly. 

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/K2-Engineering#36]
Resources item(s) from the left side should have an opposite item from the right side or the other way round
URL: http://k2engineering.stage.titanweb.com.au/resources/

Screenshot(s):
![resources - 08](https://cloud.githubusercontent.com/assets/12888048/8277411/1e77ca5a-18f5-11e5-9b63-54c2504bf1ed.jpg)

**Comment by rexcebudigital** [comment]
Note an issue on my end. pls do recheck thanks.

**Comment by romatitan** [comment]
Please check on iPad air: Portrait view
Thanks!
