### ISSUE TITLE
CTA: Font size of Contact text was set to 14px. It differs from the given design 20px.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/K2-Engineering#40]
URL: http://k2engineering.stage.titanweb.com.au/

Screenshot(s): 
![cta - 01](https://cloud.githubusercontent.com/assets/12888048/8324151/c454f642-1a7f-11e5-86cf-f0730c58da9e.jpg)

**Comment by rexcebudigital** [comment]
Other attributes like h2 and h3 ol, ul li, has its own font size.

**Comment by romatitan** [comment]
Font used was Arial, it should be Exo.
Font size was set to 16px. It should be 20.83px/21px

Screenshot(s):
![cta - 04](https://cloud.githubusercontent.com/assets/12888048/8399314/0f5f977a-1e3e-11e5-8a51-1edd077e0366.jpg)

**Comment by rexcebudigital** [comment]
I don't see this issue on my end. Please see screenshot. I took the screenshot on the stage URL.

![screenshot jpg 1655x1033](https://cloud.githubusercontent.com/assets/11186391/8400560/51d8253a-1e53-11e5-82dc-2a5d590d731f.png)
