### ISSUE TITLE
CTA: Prefooter issues.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/K2-Engineering#41]
Summary:
The CTA border container has no fixed size. 
It expands depending on the length of the contact text inputted.
Image hangs at the upper part of the CTA container.
It stated in the project scope that Footer ACF is - footer description[ wysiwyg ] , then it should accept any content format.

Please clarify the project scope regarding Footer ACF, confirm with leads and update the scope accordingly. Thanks

Screenshot(s):
![cta - 02](https://cloud.githubusercontent.com/assets/12888048/8324233/f48c6114-1a80-11e5-9ab0-364496679416.jpg)

**Comment by rexcebudigital** [comment]
Implemented the ACF Global and accepts any content. About the image there's no instruction on how to implement the image. I'm just following the design specs.
