### ISSUE TITLE
CTA: The image did not occupy the entire height of the cta background container

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/K2-Engineering#50]
Screenshot(s):
![cta - 05](https://cloud.githubusercontent.com/assets/12888048/8399700/e6c8f2fe-1e45-11e5-84f5-0d4b4719f41c.jpg)

**Comment by romatitan** [comment]
There's a space between cta image and footer background
Affected browser: Chrome
Screenshot(s):
![cta - 08](https://cloud.githubusercontent.com/assets/12888048/8446249/37275124-1fda-11e5-91df-6d58b505dcdf.jpg)

**Comment by rexcebudigital** [comment]
Its not an issue on my end. Please see the screenshot. My chrome version is Up to date.
![sample homepage title page k2 engineering supplies](https://cloud.githubusercontent.com/assets/11186391/8447185/4c6887ee-1fe7-11e5-9dde-457e290c9bfd.png)
![chrome version](https://cloud.githubusercontent.com/assets/11186391/8447186/4c958e38-1fe7-11e5-909f-354ed8d98703.jpg)

**Comment by romatitan** [comment]
Not yet fix.
My chrome version is Up to date as well.

![cta - 09](https://cloud.githubusercontent.com/assets/12888048/8470982/b3f80f54-20c5-11e5-9ecc-a931c219b0fc.jpg)

**Comment by romatitan** [comment]
This is a localized issue, reproducible on my end.
But cannot be reproduced in another browser in different machines.
I'll be monitoring this issue from time to time.
