### ISSUE TITLE
Question: For the banners on inner pages, does each banner on each page should be different from the homepage banners?

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/K2-Engineering#51]
For the banners on inner pages, does each banner on each page should be different from the homepage banners?

In admin, there are three (3) banners with pagelink for " View Range" button and it is temporarily link to "Product" page. ( reference #34 According to your Team Lead, as for now link the view range to Product page alone.)

We still have another button aside from View Range, --  the "Contact Us" button, on the banner on the inner pages. Should it link to Product page as well? or should it have a separate banner and pagelink that link to Contact Us page?

Please confirm with leads and update the scope accordingly.

Thank you.

**Comment by rexcebudigital** [comment]
The inner pages banner link is now pointing to contact us. We will just follow the design specs for this.
