### ISSUE TITLE
Product Single: Breadcrumbs details differs from the design

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/K2-Engineering#53]
Screenshot(s):

![product - 04](https://cloud.githubusercontent.com/assets/12888048/8401466/518895b6-1e61-11e5-9c0b-84dcb54bb8b4.jpg)

**Comment by romatitan** [comment]
And the breadcrumbs details under Machine Tool Accessories as well.
![machine tool accessories - 05](https://cloud.githubusercontent.com/assets/12888048/8401504/f3225f24-1e61-11e5-8e1e-68c9080efb77.jpg)

**Comment by rexcebudigital** [comment]
Please have a time to read the KB. Cheers.
https://knowledgebase.titanweb.com.au/implementation-practices/woocommerce/breadcrumbs

**Comment by romatitan** [comment]
It is correct that the breadcrumbs was implemented and placed below the page/post title but the issue is its details. It should be "K2 Engineering" alone as what the design has and not "K2 Engineering Supplies"

**Comment by rexcebudigital** [comment]
This is the right comment : It should be "K2 Engineering" alone as what the design has and not "K2 Engineering Supplies" to make the bug clear. Thanks.
