### ISSUE TITLE
Breadcrumbs for News single page should display the parent of the current task. "K2 Engineering > News > News single"

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/K2-Engineering#57]
Screenshot(s):
![news - 02](https://cloud.githubusercontent.com/assets/12888048/8425018/240c68dc-1f34-11e5-9d20-8b03fba6ef24.jpg)

**Comment by rexcebudigital** [comment]
This is the correct breadcrumbs News >Test 3 – News Complete,
the K2 Engineering appears because I manually added it using jquery.
