### ISSUE TITLE
Promotion: PDF plus (+) option was missing

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/K2-Engineering#6]
URL: http://k2engineering.stage.titanweb.com.au/promotions/
Screenshot(s):
![promotion - 01](https://cloud.githubusercontent.com/assets/12888048/8173624/028af250-1403-11e5-9ad9-daac495aea1d.jpg)

**Comment by romatitan** [comment]
Question: 
What is the function of "plus(+) " in promotions page.
Is it another page link, or an add pdf option?

**Comment by rexcebudigital** [comment]
Its is a download/open button.

**Comment by romatitan** [comment]
All pdf should be open in a new tab
