### ISSUE TITLE
Header: The sub menu container was not aligned to its parent sub menu.

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/K2-Engineering#72]
Affected browser: Chrome

![header - 06](https://cloud.githubusercontent.com/assets/12888048/8640929/a2018158-293b-11e5-9921-f45fbd711fcc.jpg)

![header - 07](https://cloud.githubusercontent.com/assets/12888048/8641063/e2a6b800-293f-11e5-8b68-c36e390577f6.jpg)

**Comment by rexcebudigital** [comment]
Hi Roma,

I don't see the issue on my end, please see my screenshot below:
![screenshot](https://cloud.githubusercontent.com/assets/11186391/8643246/dd34a08e-2963-11e5-8910-82bff6f9e9a8.jpg)

But I am able to see the issue when I made my browser view to 110%.
See screenshot below for 110% view:
![screenshot](https://cloud.githubusercontent.com/assets/11186391/8643264/295ad550-2964-11e5-8053-cf267f8c6643.jpg)


Can you try to press ctrl+0 to make the browser view back to default view.
Please let me know if the issue still exist. Thanks.

**Comment by romatitan** [comment]
Hi Rex,

I've still seen a sub menu container that is not aligned properly (100% view).

1. Click "Catalogues"
2. Hover the mouse on "Thank You"

Here's the screenshot.
![header - 08](https://cloud.githubusercontent.com/assets/12888048/8664213/ca9d6430-2a06-11e5-8636-edcd23ce9aea.jpg)

**Comment by rexcebudigital** [comment]
Hi Roma, It is now fixes. Thanks for this. Please kindly let me know if the bug still exist.
Please see screenshot below for the stage URL:
![screenshot](https://cloud.githubusercontent.com/assets/11186391/8664725/af927ed0-2a0d-11e5-8387-0dd458cad641.jpg)

**Comment by romatitan** [comment]
Verifided fixed. :)
